"use client";

import React, { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import {
  Upload,
  AlertTriangle,
  CheckCircle,
  Clock,
  Shield,
  FileCheck,
  Brain,
  Zap,
  Star,
  Plus,
  Minus,
  Check,
  ArrowRight,
  Globe,
} from "lucide-react";

// Types for live activity stream
interface ScanActivity {
  id: string;
  name: string;
  institution: string;
  type: string;
  similarity: number;
  ai: number;
  time: string;
}

const INITIAL_ACTIVITIES: ScanActivity[] = [
  { id: "1", name: "Kasun P.", institution: "University of Kelaniya", type: "Thesis Draft", similarity: 12, ai: 0, time: "2 min ago" },
  { id: "2", name: "Dilini S.", institution: "SLIIT", type: "Document 2", similarity: 8, ai: 14, time: "5 min ago" },
  { id: "3", name: "Tariq A.", institution: "University of Colombo", type: "Research Paper", similarity: 18, ai: 5, time: "9 min ago" },
  { id: "4", name: "Fathima R.", institution: "UOM - Moratuwa", type: "Dissertation", similarity: 4, ai: 0, time: "12 min ago" },
  { id: "5", name: "Sanduni W.", institution: "University of Peradeniya", type: "Literature Review", similarity: 15, ai: 45, time: "18 min ago" },
  { id: "6", name: "Minidu K.", institution: "KDU", type: "Final Report", similarity: 9, ai: 8, time: "25 min ago" },
];

const FAQS = [
  {
    q: "How do you generate the reports?",
    a: "Once you upload your document, our platform routes it through a verified Turnitin® Instructor account via a secure API connection. The system creates a read-only submission, runs the similarity and AI analysis, exports the official PDF reports, and then cleans up the session. The entire process is automated and human-free."
  },
  {
    q: "How long does it take?",
    a: "Most reports are fully generated and available for download within 2 to 5 minutes. During peak global academic periods (such as university finals weeks) or for extremely long papers, processing can take slightly longer."
  },
  {
    q: "Will my file be saved in Turnitin?",
    a: "No. We guarantee that your documents will never be indexed or saved in Turnitin’s database. Our systems use verified Instructor accounts set strictly to \"No-Repository\" mode. Turnitin reads your paper to generate the report but discards it immediately after."
  },
  {
    q: "What reports do I get?",
    a: "For every document checked, you receive two official PDF reports exported directly from Turnitin Feedback Studio: a Similarity Report (showing text highlights and matching sources) and an AI Detection Report (predicting text written by models like ChatGPT, Gemini, or Claude)."
  },
  {
    q: "What does the percentage mean in the AI report?",
    a: "The AI percentage (from 0% to 100%) represents the portion of text in your document that Turnitin's machine learning model predicts was generated by an AI writing assistant. For example, a 30% score indicates that AI-patterned language was detected in roughly 30% of your paper."
  },
  {
    q: "Are these the same reports universities get?",
    a: "Yes, they are 100% identical. Because the reports are generated using the official Turnitin Feedback Studio backend through verified Instructor nodes, the layout, match breakdown, and source highlights match exactly what university faculty members see."
  },
  {
    q: "What is a slot?",
    a: "A slot (or scan credit) represents a single scan balance. One slot allows you to upload and check one document for both similarity and AI writing detection. You can purchase slots in packages based on your requirements."
  },
  {
    q: "What if my slots expire?",
    a: "Purchased slots are valid for 30 days from their activation date. Any unused slots will automatically expire after 30 days, so we recommend using your checks within this active period."
  },
  {
    q: "Can I get a refund?",
    a: "Yes. If a scan fails due to a system error, API disconnection, or provider issue, the slot is automatically returned to your balance. We also issue manual refunds or re-credits if you encounter technical errors during the generation process that prevent you from obtaining a readable report."
  },
  {
    q: "Is my file safe?",
    a: "Absolutely. We enforce strict data privacy standards. All files are processed securely via SSL encryption, submitted directly to the Turnitin node, and automatically deleted from our servers permanently exactly 24 hours after upload. No human has access to read your work."
  },
  {
    q: "Can I check my paper multiple times?",
    a: "Yes. Since we scan in No-Repository mode, your previous drafts are never stored. You can upload Draft 1, make edits to resolve highlighted issues, and upload Draft 2 using another slot. Subsequent checks will never match against your own prior drafts."
  },
  {
    q: "Why does my report return a 0% AI detection score or say 'AI detection not available'?",
    a: "Turnitin's AI detection engine requires the document to contain at least 300 words of editable prose. If your document or section is shorter than 300 words, Turnitin disables the AI detector entirely to prevent false positives. Additionally, the AI model currently only evaluates English-language documents."
  },
  {
    q: "Can Turnitin detect AI-generated text that has been paraphrased?",
    a: "Turnitin's AI writing detection model is updated regularly to flag signatures left by popular paraphrasing tools (such as QuillBot). Additionally, heavy paraphrasing often results in awkward phrasing that Turnitin flags as highly predictable, raising the AI probability score."
  },
  {
    q: "What should I do if my paper is flagged with a false-positive AI score?",
    a: "If you wrote the paper yourself but received a high AI score, you can defend your work by showing your document's version history (e.g., Google Docs or MS Word edit histories) which proves your step-by-step writing process. You can also provide your research notes, outlines, and source materials to demonstrate your original research."
  },
  {
    q: "What is the difference between a Similarity Index and Plagiarism?",
    a: "A similarity index is an automated measure of text overlap. Plagiarism is the ethical violation of presenting someone else's work as your own. A high similarity score can be completely ethical if it consists of properly quoted and cited sources, standard equations, or legal definitions."
  },
  {
    q: "What similarity percentage is considered safe or acceptable for submission?",
    a: "There is no universal 'safe' score. Most academic institutions set their own thresholds (usually between 10% and 20%). However, instructors review the actual report, not just the number. A 5% match that is copied directly without quotes can be plagiarism, whereas a 25% match consisting of cited quotes and references is often completely acceptable."
  },
  {
    q: "Can I exclude my bibliography, reference list, and quotes from the similarity score?",
    a: "Yes. Although the initial PDF displays the overall index, the Turnitin Feedback Studio report identifies quotes and bibliographies. Tutors (and our reports) can filter out these sections to show your 'clean' similarity score. You can view the matching sources breakdown to see exactly how much of the percentage is due to your reference list."
  },
  {
    q: "Why does the report flag common, generic academic phrases as similarity matches?",
    a: "Turnitin's algorithms scan for sequences of consecutive words. It is normal for standard academic idioms or transitions to flag matches. Tutors expect to see these minor, fragmented matches and ignore them during evaluation."
  },
  {
    q: "Can Turnitin detect paraphrased content, or does it only search for exact matches?",
    a: "Turnitin does not just scan for word-for-word copies; it analyzes sentence structures, clauses, and synonyms. If a paragraph is paraphrased but maintains the exact structural syntax and argument flow of the original source, Turnitin's algorithm will still highlight it as a match."
  }
];

export default function Home() {
  const [activeReportTab, setActiveReportTab] = useState<"similarity" | "ai">("similarity");
  const [openFaqs, setOpenFaqs] = useState<Record<number, boolean>>({});
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [loadingRedirect, setLoadingRedirect] = useState(false);
  const [activities, setActivities] = useState<ScanActivity[]>(INITIAL_ACTIVITIES);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const router = useRouter();

  // Simulate scrolling live activity logs
  useEffect(() => {
    const interval = setInterval(() => {
      const names = ["Amesh M.", "Nipuni F.", "Roshan T.", "Shenali P.", "Vinu K.", "John D.", "Saman H."];
      const institutions = [
        "University of Colombo", 
        "University of Kelaniya", 
        "SLIIT", 
        "University of Moratuwa", 
        "University of Peradeniya", 
        "Sabaragamuwa University",
        "Eastern University"
      ];
      const types = ["Thesis Chapter 3", "Final Dissertation", "Math Document", "Economics Essay", "Proposal Draft"];
      
      const newActivity: ScanActivity = {
        id: Date.now().toString(),
        name: names[Math.floor(Math.random() * names.length)],
        institution: institutions[Math.floor(Math.random() * institutions.length)],
        type: types[Math.floor(Math.random() * types.length)],
        similarity: Math.floor(Math.random() * 25) + 1,
        ai: Math.random() > 0.4 ? Math.floor(Math.random() * 85) : 0,
        time: "Just now"
      };

      setActivities(prev => {
        const updated = [newActivity, ...prev.slice(0, 5)];
        return updated;
      });
    }, 5000);

    return () => clearInterval(interval);
  }, []);

  const toggleFaq = (index: number) => {
    setOpenFaqs(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => {
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const file = e.dataTransfer.files[0];
      processSelectedFile(file.name);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      processSelectedFile(e.target.files[0].name);
    }
  };

  const processSelectedFile = (fileName: string) => {
    const ext = fileName.split(".").pop()?.toLowerCase();
    if (ext !== "pdf" && ext !== "docx" && ext !== "doc") {
      alert("Invalid file format. Please upload PDF, DOCX, or DOC.");
      return;
    }
    setSelectedFile(fileName);
    setLoadingRedirect(true);
    // Simulate redirection delay
    setTimeout(() => {
      // Save file name in sessionStorage to grab in register/dashboard
      sessionStorage.setItem("pendingUploadFile", fileName);
      const user = localStorage.getItem("currentUser");
      if (user) {
        router.push("/dashboard");
      } else {
        router.push(`/auth/register?file=${encodeURIComponent(fileName)}`);
      }
    }, 1500);
  };

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />

      <main className="flex-1">
        {/* Hero Section */}
        <section className="relative overflow-hidden bg-gradient-to-b from-primary/5 via-background to-background py-20 lg:py-28">
          <div className="mx-auto max-w-6xl px-6 grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            {/* Left Content */}
            <div className="lg:col-span-7 space-y-6 text-left">
              <span className="inline-flex items-center gap-1.5 rounded-full bg-primary/10 border border-primary/20 px-3.5 py-1.5 text-xs font-bold uppercase tracking-wider text-primary">
                <Check className="h-3.5 w-3.5" /> 100% No-Repository Guarantee
              </span>
              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.08] text-foreground">
                Turnitin Checker <br />
                <span className="text-primary bg-clip-text">Sri Lanka</span>
              </h1>
              <p className="text-base sm:text-lg text-muted-foreground leading-relaxed max-w-xl font-medium">
                Official Turnitin® Similarity + AI report generator. Designed strictly in No-Repository mode. Pre-submit drafts privately without ever indexing your work in university databases.
              </p>

              {/* Stats badges */}
              <div className="grid grid-cols-3 gap-4 pt-2">
                <div className="flex flex-col border-l-2 border-primary/30 pl-3">
                  <span className="text-2xl font-black text-foreground tracking-tight">8,000+</span>
                  <span className="text-xs text-muted-foreground font-semibold">Sri Lankan Students</span>
                </div>
                <div className="flex flex-col border-l-2 border-primary/30 pl-3">
                  <span className="text-2xl font-black text-foreground tracking-tight">5-30m</span>
                  <span className="text-xs text-muted-foreground font-semibold">Average Scan Time</span>
                </div>
                <div className="flex flex-col border-l-2 border-primary/30 pl-3">
                  <span className="text-2xl font-black text-foreground tracking-tight">100%</span>
                  <span className="text-xs text-muted-foreground font-semibold">Revision Safe</span>
                </div>
              </div>
            </div>

            {/* Right Dropzone */}
            <div className="lg:col-span-5">
              <div
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDrop={handleDrop}
                onClick={() => fileInputRef.current?.click()}
                className={`relative flex flex-col items-center justify-center rounded-3xl border-2 border-dashed p-8 text-center cursor-pointer transition-all duration-300 ${
                  isDragging
                    ? "border-primary bg-primary/5 scale-[1.02]"
                    : "border-border hover:border-primary/40 bg-card hover:shadow-xl hover:shadow-primary/5"
                }`}
              >
                <input
                  type="file"
                  ref={fileInputRef}
                  onChange={handleFileChange}
                  accept=".pdf,.docx,.doc"
                  className="hidden"
                />

                {loadingRedirect ? (
                  <div className="py-12 space-y-4">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
                    <p className="text-sm font-bold text-foreground">Preparing workspace for {selectedFile}...</p>
                  </div>
                ) : (
                  <div className="space-y-4 py-8">
                    <div className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                      <Upload className="h-7 w-7" />
                    </div>
                    <div className="space-y-1">
                      <p className="text-base font-extrabold text-foreground">
                        Drag & drop your file here
                      </p>
                      <p className="text-xs text-muted-foreground font-medium">
                        or click to browse from device
                      </p>
                    </div>
                    <div className="pt-2">
                      <span className="inline-block rounded-lg bg-muted px-2.5 py-1 text-[10px] font-bold text-muted-foreground uppercase tracking-wider">
                        PDF, DOCX, DOC up to 50MB
                      </span>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </section>

        {/* Warning Index Section */}
        <section className="border-y border-border/40 bg-muted/20 py-16">
          <div className="mx-auto max-w-6xl px-6 text-center space-y-8">
            <div className="max-w-2xl mx-auto space-y-3">
              <span className="inline-flex items-center gap-1.5 rounded-full bg-red-500/10 border border-red-500/20 px-3 py-1 text-xs font-bold text-red-500">
                <AlertTriangle className="h-3.5 w-3.5" /> DANGER: UNIVERSITIES PERMANENTLY INDEX PAPERS
              </span>
              <h2 className="text-3xl font-black text-foreground tracking-tight">
                Submit Drafts Directly? Big Mistake.
              </h2>
              <p className="text-sm text-muted-foreground font-medium leading-relaxed">
                If you submit a draft directly on standard university Turnitin document portals, the document might be saved into Turnitin&apos;s repository database. When you re-check or submit your final revision, it flags against your own draft as **100% Plagiarized**.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-4xl mx-auto text-left">
              <div className="bg-card border border-border p-6 rounded-2xl space-y-3">
                <div className="text-xs font-bold text-red-500 font-mono">STEP 01</div>
                <h3 className="font-extrabold text-base text-foreground leading-snug">Draft upload on standard setup</h3>
                <p className="text-xs text-muted-foreground leading-relaxed font-medium">Your university portal processes the draft but permanently indexes the text structure inside Turnitin.</p>
              </div>
              <div className="bg-card border border-border p-6 rounded-2xl space-y-3">
                <div className="text-xs font-bold text-red-500 font-mono">STEP 02</div>
                <h3 className="font-extrabold text-base text-foreground leading-snug">Review and revise locally</h3>
                <p className="text-xs text-muted-foreground leading-relaxed font-medium">You spend hours rewriting paragraphs and improving sentences based on draft notes.</p>
              </div>
              <div className="bg-card border border-border p-6 rounded-2xl space-y-3">
                <div className="text-xs font-bold text-red-500 font-mono">STEP 03</div>
                <h3 className="font-extrabold text-base text-foreground leading-snug">Final draft scan displays 100%</h3>
                <p className="text-xs text-muted-foreground leading-relaxed font-medium">Your updated copy matches sentence-by-sentence against the draft Turnitin indexed.</p>
              </div>
            </div>

            <div>
              <button
                onClick={() => router.push("/#pricing")}
                className="inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-3 text-sm font-bold text-primary-foreground hover:bg-primary/95 transition-all shadow-md shadow-primary/10"
              >
                <Shield className="h-4.5 w-4.5" />
                <span>Scan Safely Without Saving</span>
              </button>
            </div>
          </div>
        </section>

        {/* Benefits Grid */}
        <section id="features" className="py-20 border-b border-border/40 bg-background">
          <div className="mx-auto max-w-6xl px-6">
            <div className="text-center max-w-3xl mx-auto mb-16 space-y-3">
              <span className="inline-block rounded-xl bg-primary/10 border border-primary/20 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-primary">
                THE SIMILARFY DIFFERENCE
              </span>
              <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-foreground">
                Official Instructor Account. Zero Indexing.
              </h2>
              <p className="text-sm text-muted-foreground font-medium max-w-xl mx-auto">
                We route all scans through official Instructor licenses. That is why your drafts are revision-safe and never saved database-wide.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {[
                {
                  icon: <FileCheck className="h-6 w-6" />,
                  title: "Official Originality Reports",
                  desc: "Get identical similarity match index PDF charts, just like the ones university lecturers download.",
                },
                {
                  icon: <Shield className="h-6 w-6" />,
                  title: "100% No-Repository Mode",
                  desc: "Strictly set checks in read-only mode. Your draft is processed, verified, and completely discarded.",
                },
                {
                  icon: <Brain className="h-6 w-6" />,
                  title: "Advanced AI Detection",
                  desc: "Analyzes text against major language models (GPT-4, Claude, Gemini) with exact highlighted sentences.",
                },
                {
                  icon: <Clock className="h-6 w-6" />,
                  title: "Revision-Safe Checking",
                  desc: "Check draft 1, write edits, check draft 2. No duplicate flags against your own prior scans.",
                },
                {
                  icon: <Globe className="h-6 w-6" />,
                  title: "Multi-Language Scans",
                  desc: "Fully processes documents written in English, Sinhala, Tamil, and other global languages.",
                },
                {
                  icon: <CheckCircle className="h-6 w-6" />,
                  title: "24-Hour Auto-Delete",
                  desc: "Strict privacy. All uploads and reports are permanently scrubbed from our servers after 24 hours.",
                },
              ].map((benefit, i) => (
                <div key={i} className="flex flex-col bg-card border border-border/80 rounded-2xl p-8 hover:border-primary/30 hover:shadow-xl hover:shadow-primary/5 transition-all">
                  <div className="flex items-start justify-between mb-6">
                    <div className="inline-flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary">
                      {benefit.icon}
                    </div>
                    <span className="font-mono text-3xl font-black text-muted-foreground/15 select-none">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                  </div>
                  <h3 className="text-lg font-bold text-foreground mb-2">{benefit.title}</h3>
                  <p className="text-sm text-muted-foreground font-medium leading-relaxed">{benefit.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Interactive Sample Viewer Tabbed Panel */}
        <section id="samples-section" className="py-20 border-b border-border/40 bg-muted/10">
          <div className="mx-auto max-w-6xl px-6">
            <div className="text-center max-w-3xl mx-auto mb-12 space-y-3">
              <span className="inline-block rounded-xl bg-primary/10 border border-primary/20 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-primary">
                REPORT SAMPLES
              </span>
              <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-foreground">
                Explore Turnitin Feedback Studio Layouts
              </h2>
              <p className="text-sm text-muted-foreground font-medium max-w-xl mx-auto">
                Select a tab below to inspect how similarity highlights and AI percentage scorecards look inside the exported PDFs.
              </p>
            </div>

            {/* Tabs Trigger */}
            <div className="flex items-center justify-center gap-2 mb-8">
              <button
                onClick={() => setActiveReportTab("similarity")}
                className={`px-5 py-2.5 rounded-xl text-sm font-bold transition-all duration-200 cursor-pointer ${
                  activeReportTab === "similarity"
                    ? "bg-primary text-primary-foreground shadow-md shadow-primary/25"
                    : "bg-card text-muted-foreground border border-border/80 hover:text-foreground"
                }`}
              >
                Similarity Report
              </button>
              <button
                onClick={() => setActiveReportTab("ai")}
                className={`px-5 py-2.5 rounded-xl text-sm font-bold transition-all duration-200 cursor-pointer ${
                  activeReportTab === "ai"
                    ? "bg-primary text-primary-foreground shadow-md shadow-primary/25"
                    : "bg-card text-muted-foreground border border-border/80 hover:text-foreground"
                }`}
              >
                AI Detection Report
              </button>
            </div>

            {/* Document Viewer Frame */}
            <div className="mx-auto max-w-4xl border border-border rounded-2xl bg-card overflow-hidden shadow-2xl">
              {activeReportTab === "similarity" ? (
                <div className="grid grid-cols-1 md:grid-cols-12 gap-0 animate-in fade-in duration-300">
                  {/* Left Doc Body */}
                  <div className="md:col-span-8 p-6 sm:p-8 space-y-4 border-r border-border min-h-[400px] text-left">
                    <div className="flex items-center justify-between border-b border-border pb-3 mb-6">
                      <span className="text-xs font-bold text-muted-foreground font-mono">document_draft_v2.docx</span>
                      <span className="text-xs font-bold text-muted-foreground font-mono">Page 1 of 1</span>
                    </div>
                    <p className="text-sm leading-relaxed text-foreground">
                      This research examines the role of neural network architecture in optimization algorithms. 
                      <span className="bg-red-500/20 border-b-2 border-red-500 text-foreground px-1 py-0.5" title="Match 1: Internet Source">
                        The primary goal of optimization is to locate the global minimum of the loss function, preventing local minimum traps.
                      </span> 
                      Through our initial benchmarks at the Colombo institute, we observed that network width scales convergence rates non-linearly.
                    </p>
                    <p className="text-sm leading-relaxed text-foreground">
                      Moreover, researchers at the SLIIT laboratory suggest that 
                      <span className="bg-purple-500/20 border-b-2 border-purple-500 text-foreground px-1 py-0.5" title="Match 2: Student Paper">
                        learning rate decay is a crucial hyperparameter that dictates model generalization.
                      </span> 
                      This aligns with empirical curves that indicate optimization step counts are heavily dependent on adaptive moment estimation coefficients.
                    </p>
                  </div>
                  {/* Right Panel */}
                  <div className="md:col-span-4 p-6 bg-muted/10 flex flex-col justify-between text-left">
                    <div>
                      <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-4">Similarity Index</h4>
                      <div className="flex items-baseline gap-2 mb-6">
                        <span className="text-5xl font-black text-red-500">14%</span>
                        <span className="text-xs font-bold text-muted-foreground">OVERALL MATCH</span>
                      </div>
                      <h5 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-3">Primary Matches</h5>
                      <div className="space-y-3">
                        <div className="flex items-center justify-between p-2.5 rounded-lg bg-card border border-border text-xs">
                          <span className="font-semibold text-foreground flex items-center gap-1.5">
                            <span className="w-2 h-2 rounded-full bg-red-500"></span>
                            1. Internet Source
                          </span>
                          <span className="font-black text-red-500">8%</span>
                        </div>
                        <div className="flex items-center justify-between p-2.5 rounded-lg bg-card border border-border text-xs">
                          <span className="font-semibold text-foreground flex items-center gap-1.5">
                            <span className="w-2 h-2 rounded-full bg-purple-500"></span>
                            2. Student Paper
                          </span>
                          <span className="font-black text-purple-500">6%</span>
                        </div>
                      </div>
                    </div>
                    <div className="pt-6 border-t border-border/80 text-[10px] font-semibold text-muted-foreground flex items-center gap-1.5">
                      <CheckCircle className="h-3.5 w-3.5 text-primary" /> Filtered Quotes: EXCLUDED
                    </div>
                  </div>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-12 gap-0 animate-in fade-in duration-300">
                  {/* Left Doc Body */}
                  <div className="md:col-span-8 p-6 sm:p-8 space-y-4 border-r border-border min-h-[400px] text-left">
                    <div className="flex items-center justify-between border-b border-border pb-3 mb-6">
                      <span className="text-xs font-bold text-muted-foreground font-mono">artificial_intelligence.docx</span>
                      <span className="text-xs font-bold text-muted-foreground font-mono">Page 1 of 1</span>
                    </div>
                    <p className="text-sm leading-relaxed text-foreground">
                      <span className="bg-cyan-500/20 border-b-2 border-cyan-500 text-foreground px-1 py-0.5" title="98% AI Probability">
                        Artificial intelligence has experienced significant growth over the past decade, revolutionizing various sectors of modern society. In the field of healthcare, machines diagnose patterns with higher accuracy.
                      </span> 
                      In contrast, the human element of clinical assessment retains key contextual parameters that standard transformers cannot duplicate.
                    </p>
                    <p className="text-sm leading-relaxed text-foreground">
                      <span className="bg-cyan-500/20 border-b-2 border-cyan-500 text-foreground px-1 py-0.5" title="94% AI Probability">
                        The integration of neural layers in computer vision algorithms enables automatic classification. This technique parses matrices in parallel pipelines to expedite the inference cycle.
                      </span> 
                      However, high power consumption and hardware limits remain optimization challenges.
                    </p>
                  </div>
                  {/* Right Panel */}
                  <div className="md:col-span-4 p-6 bg-muted/10 flex flex-col justify-between text-left">
                    <div>
                      <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-4">AI Detection Score</h4>
                      <div className="flex items-baseline gap-2 mb-6">
                        <span className="text-5xl font-black text-cyan-500">68%</span>
                        <span className="text-xs font-bold text-muted-foreground font-mono">AI GENERATED</span>
                      </div>
                      <div className="p-3 bg-cyan-500/5 border border-cyan-500/20 rounded-xl text-xs space-y-2 leading-relaxed font-semibold text-cyan-600 dark:text-cyan-400">
                        <p>Our model predicts that 68% of the text was generated by an AI tool like ChatGPT, Gemini, or Claude.</p>
                        <p>Turnitin underlines AI phrases in blue for easy editing.</p>
                      </div>
                    </div>
                    <div className="pt-6 border-t border-border/80 text-[10px] font-semibold text-muted-foreground flex items-center gap-1.5">
                      <Brain className="h-3.5 w-3.5 text-cyan-500" /> Language: ENGLISH ONLY
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </section>

        {/* How it works */}
        <section id="how-it-works" className="py-20 border-b border-border/40 bg-background">
          <div className="mx-auto max-w-6xl px-6">
            <div className="text-center max-w-2xl mx-auto mb-16 space-y-3">
              <span className="inline-block rounded-xl bg-primary/10 border border-primary/20 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-primary">
                HOW IT WORKS
              </span>
              <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-foreground">
                Get Reports in 3 Simple Steps
              </h2>
              <p className="text-sm text-muted-foreground font-medium max-w-xl mx-auto">
                Fast, automated, and secure. Scans complete within minutes.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
              {[
                {
                  step: "01",
                  title: "Purchase Scan Credits",
                  desc: "Select a scan slot package that fits your requirements. Credits load immediately on confirmation.",
                },
                {
                  step: "02",
                  title: "Upload Document",
                  desc: "Drop your PDF, DOCX, or DOC file in the dashboard panel. Your file is processed in No-Repository mode.",
                },
                {
                  step: "03",
                  title: "Download PDFs",
                  desc: "Get both Similarity index reports and AI detection breakdowns from the dashboard as official files.",
                },
              ].map((stepItem, i) => (
                <div key={i} className="bg-card border border-border rounded-2xl p-8 space-y-4 hover:border-primary/20 transition-all text-left">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-xs font-bold tracking-widest text-primary bg-primary/10 px-2.5 py-1 rounded-lg">
                      STEP {stepItem.step}
                    </span>
                  </div>
                  <h3 className="font-extrabold text-lg text-foreground">{stepItem.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed font-medium">{stepItem.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Pricing Cards Grid */}
        <section id="pricing" className="py-20 border-b border-border/40 bg-background relative overflow-hidden">
          <div className="mx-auto max-w-6xl px-6">
            <div className="text-center max-w-3xl mx-auto mb-16 space-y-3">
              <span className="inline-block rounded-xl bg-primary/10 border border-primary/20 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-primary">
                PRICING
              </span>
              <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-foreground">
                Transparent Pay-As-You-Go Packages
              </h2>
              <p className="text-sm text-muted-foreground font-medium max-w-xl mx-auto">
                No monthly subscriptions. Buy scan slots as needed. Each scan includes both Similarity and AI writing analysis.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl mx-auto">
              {[
                { name: "Single Check", slots: 1, price: "1,000", popular: false, desc: "For single document check" },
                { name: "Revision Pack", slots: 5, price: "4,750", popular: true, desc: "Best for draft improvements" },
                { name: "Scholar Pro", slots: 10, price: "7,500", popular: false, desc: "Ideal for dissertation check" },
                { name: "Editor Elite", slots: 25, price: "21,250", popular: false, desc: "For researchers and tutors" },
                { name: "Department", slots: 50, price: "40,000", popular: false, desc: "Great for research teams" },
                { name: "Institution", slots: 100, price: "75,000", popular: false, desc: "Best value for departments" },
              ].map((pkg, i) => (
                <div
                  key={i}
                  className={`bg-card border rounded-3xl p-7 flex flex-col justify-between transition-all duration-200 relative ${
                    pkg.popular
                      ? "border-primary shadow-xl shadow-primary/5 ring-1 ring-primary"
                      : "border-border hover:border-primary/20"
                  }`}
                >
                  {pkg.popular && (
                    <span className="absolute -top-3 left-1/2 -translate-x-1/2 bg-primary text-primary-foreground text-[10px] font-black tracking-wider uppercase px-3 py-1 rounded-full">
                      Most Popular
                    </span>
                  )}
                  <div className="space-y-4 text-left">
                    <div>
                      <h4 className="text-sm font-bold text-muted-foreground">{pkg.name}</h4>
                      <div className="flex items-baseline gap-1 mt-2">
                        <span className="text-3xl font-black text-foreground">{pkg.slots}</span>
                        <span className="text-xs font-semibold text-muted-foreground">Scan Credits</span>
                      </div>
                      <p className="text-xs text-muted-foreground/80 mt-1 font-medium">{pkg.desc}</p>
                    </div>

                    <hr className="border-border/40" />

                    <div className="space-y-1">
                      <span className="text-xs font-bold text-muted-foreground">PRICE</span>
                      <div className="flex items-baseline gap-1">
                        <span className="text-xs font-extrabold text-foreground">LKR</span>
                        <span className="text-3xl font-black text-foreground">{pkg.price}</span>
                      </div>
                    </div>

                    <ul className="space-y-2 pt-2 text-xs font-semibold text-muted-foreground">
                      <li className="flex items-center gap-2">
                        <Check className="h-4 w-4 text-primary shrink-0" />
                        <span>Similarity Report (PDF)</span>
                      </li>
                      <li className="flex items-center gap-2">
                        <Check className="h-4 w-4 text-primary shrink-0" />
                        <span>AI Writing Detection (PDF)</span>
                      </li>
                      <li className="flex items-center gap-2">
                        <Check className="h-4 w-4 text-primary shrink-0" />
                        <span>No-Repository scan mode</span>
                      </li>
                      <li className="flex items-center gap-2">
                        <Check className="h-4 w-4 text-primary shrink-0" />
                        <span>Credits valid for 30 days</span>
                      </li>
                    </ul>
                  </div>

                  <div className="pt-6">
                    <button
                      onClick={() => {
                        const storedUser = localStorage.getItem("currentUser");
                        if (storedUser) {
                          router.push(`/dashboard?buy=${pkg.slots}&price=${pkg.price.replace(",", "")}`);
                        } else {
                          router.push(`/auth/register?buy=${pkg.slots}&price=${pkg.price.replace(",", "")}`);
                        }
                      }}
                      className={`w-full justify-center py-3 rounded-xl text-sm font-extrabold transition-all duration-200 cursor-pointer ${
                        pkg.popular
                          ? "bg-primary text-primary-foreground hover:bg-primary/95 shadow-md shadow-primary/25"
                          : "bg-secondary text-foreground hover:bg-muted"
                      }`}
                    >
                      Buy Credits
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Live Scan Activity Feed */}
        <section className="py-20 border-b border-border/40 bg-background relative overflow-hidden">
          <div className="mx-auto max-w-4xl px-6">
            <div className="text-center max-w-2xl mx-auto mb-12 space-y-3">
              <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-600 dark:text-emerald-400">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
                Live Scanning Stream
              </span>
              <h2 className="text-3xl font-extrabold tracking-tight text-foreground">
                Students Scanning Right Now
              </h2>
              <p className="text-sm text-muted-foreground font-medium max-w-xl mx-auto">
                Real-time feed of uploads processed through our No-Repository nodes. Files auto-deleted on finish.
              </p>
            </div>

            {/* List */}
            <div className="relative border border-border rounded-2xl bg-card p-4 h-[350px] overflow-hidden">
              <div className="absolute top-0 left-0 right-0 h-10 bg-gradient-to-b from-card to-transparent z-10 pointer-events-none"></div>
              <div className="absolute bottom-0 left-0 right-0 h-10 bg-gradient-to-t from-card to-transparent z-10 pointer-events-none"></div>
              
              <div className="flex flex-col gap-3 h-full overflow-y-auto">
                {activities.map((act) => (
                  <div
                    key={act.id}
                    className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-xl border border-border bg-background text-left transition-all duration-300 animate-in slide-in-from-top-4 duration-300"
                  >
                    <div className="flex items-center gap-3">
                      <div className="h-9 w-9 rounded-xl bg-primary/10 text-primary font-bold flex items-center justify-center shrink-0">
                        {act.name[0]}
                      </div>
                      <div>
                        <div className="flex items-baseline gap-1.5">
                          <span className="text-sm font-bold text-foreground">{act.name}</span>
                          <span className="text-[10px] text-muted-foreground font-mono font-bold tracking-wider">{act.time}</span>
                        </div>
                        <p className="text-xs text-muted-foreground font-semibold">{act.institution} · {act.type}</p>
                      </div>
                    </div>
                    {/* Scores */}
                    <div className="flex items-center gap-3">
                      <div className="px-3 py-1 bg-red-500/10 border border-red-500/20 text-red-500 text-xs font-black rounded-lg">
                        Similarity: {act.similarity}%
                      </div>
                      <div className="px-3 py-1 bg-cyan-500/10 border border-cyan-500/20 text-cyan-500 text-xs font-black rounded-lg">
                        AI: {act.ai}%
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Reviews Section */}
        <section className="py-20 border-b border-border/40 bg-muted/10">
          <div className="mx-auto max-w-6xl px-6">
            <div className="text-center max-w-3xl mx-auto mb-16 space-y-3">
              <span className="inline-block rounded-xl bg-primary/10 border border-primary/20 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-primary">
                VERIFIED REVIEWS
              </span>
              <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-foreground">
                Trusted by Researchers across Sri Lanka
              </h2>
              <p className="text-sm text-muted-foreground font-medium max-w-xl mx-auto">
                Join thousands of university students protecting drafts prior to their final submissions.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {[
                {
                  name: "Kasun Perera",
                  role: "PhD Candidate",
                  uni: "University of Kelaniya",
                  review: "The only platform I trust before submitting draft chapters. No-Repository checks are highly secure — I can check multiple revisions without self-plagiarism flags.",
                  initial: "K",
                },
                {
                  name: "Dilini Senanayake",
                  role: "Undergraduate Student",
                  uni: "SLIIT",
                  review: "Absolutely saved my final research thesis. The turnitin AI report highlights exactly which sentences look generated, so I could edit it with complete transparency.",
                  initial: "D",
                },
                {
                  name: "Tariq Ahamed",
                  role: "MSc Student",
                  uni: "University of Colombo",
                  review: "Super fast reports within 10 minutes. The checkout options support local Sri Lankan cards and payment confirmations are instantaneous.",
                  initial: "T",
                },
              ].map((rev, i) => (
                <div key={i} className="bg-card border border-border rounded-2xl p-6 space-y-4 text-left flex flex-col justify-between">
                  <div className="space-y-3">
                    <div className="flex gap-0.5 text-primary">
                      {[...Array(5)].map((_, index) => (
                        <Star key={index} className="h-3.5 w-3.5 fill-current" />
                      ))}
                    </div>
                    <p className="text-sm text-muted-foreground font-semibold leading-relaxed italic">
                      “{rev.review}”
                    </p>
                  </div>
                  <div className="flex items-center gap-3 border-t border-border pt-4">
                    <div className="h-9 w-9 rounded-xl bg-primary/10 border border-primary/15 text-primary font-bold text-sm flex items-center justify-center shrink-0">
                      {rev.initial}
                    </div>
                    <div>
                      <p className="text-sm font-bold text-foreground leading-none mb-1">{rev.name}</p>
                      <p className="text-[10px] text-muted-foreground font-mono font-bold tracking-wide">
                        {rev.role} · {rev.uni}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQs Accordion */}
        <section className="py-20 border-b border-border/40 bg-background">
          <div className="mx-auto max-w-3xl px-6">
            <div className="text-center max-w-2xl mx-auto mb-12 space-y-3">
              <span className="inline-block rounded-xl bg-primary/10 border border-primary/20 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-primary">
                FAQ
              </span>
              <h2 className="text-3xl font-extrabold tracking-tight text-foreground">
                Questions About No-Repository Scans
              </h2>
              <p className="text-sm text-muted-foreground font-medium max-w-xl mx-auto">
                Everything you need to know before your first draft check.
              </p>
            </div>

            <div className="space-y-3 text-left">
              {FAQS.map((faq, i) => {
                const isOpen = !!openFaqs[i];
                return (
                  <div
                    key={i}
                    className="border rounded-2xl overflow-hidden bg-card border-border hover:border-primary/20 transition-all duration-200"
                  >
                    <button
                      onClick={() => toggleFaq(i)}
                      className="w-full flex items-center justify-between gap-4 px-5 py-4 text-sm font-bold text-left cursor-pointer focus:outline-none text-foreground hover:text-primary transition-colors"
                    >
                      <span>{faq.q}</span>
                      {isOpen ? (
                        <Minus className="h-4 w-4 text-primary shrink-0" />
                      ) : (
                        <Plus className="h-4 w-4 text-primary shrink-0" />
                      )}
                    </button>

                    <div
                      className={`transition-all duration-300 ease-in-out overflow-hidden ${
                        isOpen ? "max-h-[300px] border-t border-border/30" : "max-h-0"
                      }`}
                    >
                      <div className="px-5 py-4 text-sm text-muted-foreground/90 leading-relaxed font-medium">
                        {faq.a}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* Bottom CTA Banner */}
        <section className="py-24 bg-primary text-primary-foreground relative overflow-hidden text-center">
          <div className="absolute top-0 left-1/2 w-[600px] h-[300px] bg-white/5 rounded-full blur-[100px] pointer-events-none -translate-x-1/2 -translate-y-1/2"></div>
          <div className="relative z-10 mx-auto max-w-4xl px-6 flex flex-col items-center justify-center space-y-6">
            <span className="inline-flex items-center gap-1.5 bg-white/15 border border-white/25 rounded-full px-4 py-1 text-[10px] font-bold uppercase tracking-widest text-white">
              <Zap className="h-3.5 w-3.5 fill-current animate-pulse" /> GET STARTED
            </span>
            <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight text-white leading-tight">
              Ready to check your paper?
            </h2>
            <p className="text-sm sm:text-base text-white/80 font-medium leading-relaxed max-w-lg mx-auto">
              Create an account, choose a plan, and run your draft checks with verified Turnitin reports in seconds.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 w-full sm:w-auto pt-2">
              <button
                onClick={() => router.push("/auth/register")}
                className="inline-flex items-center justify-center gap-2 whitespace-nowrap focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 border border-transparent h-12 px-8 text-sm font-extrabold rounded-xl bg-white text-primary hover:bg-white/95 transition-all duration-200 hover:scale-[1.02] w-full sm:w-52"
              >
                <span>Get Started Now</span>
                <ArrowRight className="h-4 w-4" />
              </button>
              <button
                onClick={() => router.push("/#pricing")}
                className="inline-flex items-center justify-center gap-2 whitespace-nowrap focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 h-12 px-8 text-sm font-extrabold rounded-xl border border-white/30 bg-transparent text-white hover:bg-white/10 transition-all duration-200 w-full sm:w-52"
              >
                View Pricing Plans
              </button>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
